version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tienda-backend-app
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html                # monta TODO tu proyecto, incluido .env
            - vendor:/var/www/html/vendor     # guarda vendor en volumen para no reinstalar cada vez
        env_file:
            - .env                            # incluye tu .env real
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: host.docker.internal     # conecta al MySQL que corre en tu host
            DB_PORT: "3309"                   # tu puerto real de MySQL
            DB_DATABASE: Tienda
            DB_USERNAME: root
            DB_PASSWORD: root123456

volumes:
    vendor:
