version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tienda-backend-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html:cached
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - /var/www/html/storage/framework/cache
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql_container
            DB_PORT: "3306"
            DB_DATABASE: Tienda
            DB_USERNAME: root
            DB_PASSWORD: root123456
        networks:
            - tienda-net

networks:
    tienda-net:
        external: true
